# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40dd6d6a94f889ea982a6145be493c2c2a99b07bc43b6c199e01de9c5788f0a2b06df40c9589f12feb23c494f22b71705ed7bfecd290d9bd977eb5f50de66375

test:
  secret_key_base: 3780d0c19624d85b5a0d9d5101154eb3eb78626f9ca0f201300e47abca42072977853d2a3cbcb45343de85b9e7ba315a85c34b2718872863a9f8863f1ea87569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
